{"bug_class": "PROVER", "kind": "ERROR", "bug_type": "NULL_DEREFERENCE", "qualifier": "object `Scope.path` last accessed on line 464  at line 464.", "severity": "HIGH", "visibility": "user", "line": 464, "column": -1, "procedure": "String Scope.extendPath(String)", "procedure_id": "org.yinwang.pysonar.Scope.extendPath(java.lang.String):java.lang.String.49b16c2d5b6ddac942eac1f5b6632eaf", "procedure_start_line": 460, "file": "src/main/java/org/yinwang/pysonar/Scope.java", "bug_trace": [{"level": 0, "filename": "src/main/java/org/yinwang/pysonar/Scope.java", "line_number": 460, "column_number": -1, "description": "start of procedure extendPath(...)"}, {"level": 0, "filename": "src/main/java/org/yinwang/pysonar/Scope.java", "line_number": 461, "column_number": -1, "description": "Taking false branch"}, {"level": 0, "filename": "src/main/java/org/yinwang/pysonar/Scope.java", "line_number": 464, "column_number": -1, "description": ""}], "key": "Scope.java|extendPath|NULL_DEREFERENCE", "node_key": "ba2a084247c0b6edee2ebcaa843f00b1", "hash": "6c17a8f7e923b41e55534e19725fe1b1", "bug_type_hum": "Null Dereference", "censored_reason": ""}