{"hash": "46e146db975181c3de2e0ebec8e25d9fa610c08d", "message": "Fix tests that intend to check that an error is thrown but don't.\n\nTests of a testing API often look like this:\n\n\ttry {\n\t\trunATestThatShouldFail();\n\t\tfail();\n\t} catch (AssertionError expected) {\n\t}\n\nHowever, the catch() block can catch not only the expected failure from runATestThatShouldFail() but also the \"test did not fail when it should have\" failure from fail().\n-------------\nCreated by MOE: https://github.com/google/moe\nMOE_MIGRATED_REVID=118941782", "file_num_lines": 64, "diff_parsed": {"added": [[68, "      throw new Error();"]], "deleted": [[68, "      fail();"]]}, "num_lines_added": 1, "num_lines_removed": 1}